name: Update Badges

on:
  workflow_run:
    workflows: ["Main CI/CD Pipeline", "Security Scanning", "Build and Deploy"]
    types:
      - completed
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-badges:
    name: Update README Badges
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get workflow status
      id: workflows
      run: |
        # Get CI/CD status
        CI_STATUS=$(gh api repos/${{ github.repository }}/actions/workflows/main-ci.yml/badge.svg --jq '.badge_url' || echo "unknown")
        echo "CI_STATUS=$CI_STATUS" >> $GITHUB_OUTPUT
        
        # Get coverage percentage from latest artifacts
        COVERAGE=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name == "coverage-reports") | .created_at' | head -1 || echo "0")
        echo "COVERAGE=$COVERAGE" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Update README with dynamic badges
      run: |
        # This is a placeholder for badge updates
        # In practice, badges auto-update via their URLs
        echo "Badges are configured with dynamic URLs"
        
    - name: Verify badge URLs
      run: |
        # Check that all badge URLs are working
        urls=(
          "https://github.com/${{ github.repository }}/actions/workflows/main-ci.yml/badge.svg"
          "https://github.com/${{ github.repository }}/actions/workflows/security.yml/badge.svg"
          "https://github.com/${{ github.repository }}/actions/workflows/deploy.yml/badge.svg"
          "https://codecov.io/gh/${{ github.repository }}/branch/main/graph/badge.svg"
        )
        
        for url in "${urls[@]}"; do
          if curl -f -s -o /dev/null "$url"; then
            echo "✅ Badge URL working: $url"
          else
            echo "❌ Badge URL not working: $url"
          fi
        done