apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chm.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "chm.labels" . | nindent 4 }}
    app: chm
    component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chm.selectorLabels" . | nindent 6 }}
      app: chm
      component: backend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.app.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "chm.selectorLabels" . | nindent 8 }}
        app: chm
        component: backend
        version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.app.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "chm.fullname" . }}-secret
              key: database-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "chm.fullname" . }}-config
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "chm.fullname" . }}-secret
              key: secret-key
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "chm.fullname" . }}-config
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: {{ include "chm.fullname" . }}-config
              key: celery-result-backend
        {{- range $key, $value := .Values.app.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.app.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.app.livenessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.app.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.app.readinessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.app.resources | nindent 12 }}
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        {{- if .Values.persistence.audit.enabled }}
        - name: audit-logs
          mountPath: {{ .Values.persistence.audit.mountPath }}
        {{- end }}
      volumes:
      - name: logs
        emptyDir: {}
      {{- if .Values.persistence.audit.enabled }}
      - name: audit-logs
        persistentVolumeClaim:
          claimName: {{ include "chm.fullname" . }}-audit-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}