{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "chm.labels" . | nindent 4 }}
    monitoring: prometheus
{{- end }}