apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: chm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: chm:v2.0.0
        command: ["celery", "-A", "backend.tasks.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chm-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: chm-config
              key: redis-url
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: chm-config
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: chm-config
              key: celery-result-backend
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: chm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: chm:v2.0.0
        command: ["celery", "-A", "backend.tasks.celery_app", "beat", "--loglevel=info"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chm-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: chm-config
              key: redis-url
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: chm-config
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: chm-config
              key: celery-result-backend
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"