apiVersion: v1
kind: ServiceAccount
metadata:
  name: chm-service-account
  namespace: chm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chm-role
  namespace: chm
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chm-role-binding
  namespace: chm
subjects:
- kind: ServiceAccount
  name: chm-service-account
  namespace: chm
roleRef:
  kind: Role
  name: chm-role
  apiGroup: rbac.authorization.k8s.io