# Codecov configuration for CHM
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        threshold: 1%
        target: 70%
        base: auto
    patch:
      default:
        threshold: 1%
        target: 70%
        base: auto

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "test_*"
  - "**/migrations/"
  - "**/conftest.py"
  - "setup.py"
  - "docs/"
  - "scripts/"
  - "frontend/"
  - "**/__pycache__/"

github_checks:
  annotations: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: CHM
        type: project
        target: 70%
